models:
  llm_small:
    endpoint: "https://api.idg.vnpt.vn/data-service/v1/chat/completions/vnptai-hackathon-small"
    model: "vnptai_hackathon_small"
    authorization: ""
    token_id: ""
    token_key: ""
    temperature: 0.3
    top_p: 0.9      
    top_k: 10          
    max_tokens: 50 
    quota_per_day: 1000  # limit API

  # llm_large:
  #   endpoint: "https://api.idg.vnpt.vn/data-service/v1/chat/completions/vnptai-hackathon-large"
  #   model: "vnptai_hackathon_large"
  #   authorization: "YOUR_BIG_TOKEN"
  #   token_id: "YOUR_BIG_TOKEN_ID"
  #   token_key: "YOUR_BIG_TOKEN_KEY"
  #   temperature: 0.6
  #   top_p: 1.0
  #   top_k: 40
  #   max_tokens: 200
  #   quota_per_day: 500
